[book]
authors = ["Connor Horman"]
language = "en"
src = "src"
title = "Skyarch ISA"

[preprocessor.links]

[preprocessor.tracey]

[output.markdown]

[output.html]


# [output.epub-fancy]
# optional = true
# output = ["part", "full"]
# always-include = ["COPYRIGHT.md", "COPYRIGHT-STUB.md"]

# [output.epub-fancy.file-ids]
